# Generated by Django 2.2.4 on 2019-09-23 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='fulname',
            field=models.CharField(default='Abinash', max_length=100),
        ),
    ]
